apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssg-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: ssg
  accessModes:
    - ReadWriteMany
