apiVersion: v1
kind: PersistentVolume
metadata:
  name: ssg-pv
spec:
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
  hostPath:
    path: /data
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ssg
